colinlboyledotcom/Controllers/NewsletterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using colinlboyledotcom.Models;
using colinlboyledotcom.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace colinlboyledotcom.Controllers
{
    public class NewsletterController : Controller
    {
        private readonly SubscribeRepository subRepository;

        public NewsletterController(IConfiguration configuration)
        {
            subRepository = new SubscribeRepository(configuration);
        }

        //POST: subscribe
        [HttpPost]
        public ActionResult Subscribe(string email)
        {
            Subscriber subscribe = new Subscriber();
            subscribe.email = email;
            if (User.Identity.Name != null)
            {
                subscribe.username = User.Identity.Name;
            }
            subscribe.subscribeddate = DateTime.Now;
            subRepository.Add(subscribe);
            return RedirectToAction("index", "home");
        }
    }
}

colinlboyledotcom/Views/Shared/AuthorWidgetPartial.cshtml
<!--Author Widget-->
<aside class="col-sm-12 m0 widget-author widget">
    <div class="widget-author-inner row">
        <div class="author-avatar row"><a href="#"><img src="/images/colin.jpg" alt="" class="img-circle"></a></div>
        <a href="#"><h2 class="author-name">Colin Boyle</h2></a>
        <h5 class="author-title">web designer</h5>
        <p>I am an aspiring web developer and frequent software dabbler. I write about those things here. Curiousity is my weapon
            of choice. You've been warned!</p>
        @*<a href="#" class="know-more">know more</a>*@
        @Html.ActionLink("know more", "about", "home", null, new { @class = "know-more" })
    </div>
    <ul class="nav social-nav">
        <li><a href="https://twitter.com/Colin_Boyle"><i class="fa fa-twitter"></i></a></li>
        <li><a href="https://www.facebook.com/colin.boyle.927"><i class="fa fa-facebook-official"></i></a></li>
        <li><a href="https://www.instagram.com/colinboyle/"><i class="fa fa-instagram"></i></a></li>
        <li><a href="mailto:colin.boyle93@gmail.com"><i class="fa fa-envelope"></i></a></li>
        <li><a href="sms://+14023120970"><i class="fa fa-mobile"></i></a></li>
    </ul>
</aside>

colinlboyledotcom/Views/Shared/FacebookWidgetPartial.cshtml
<!--Facebook Widget-->
<aside class="row m0 widget widget-facebook">
    <div class="widget-inner widget-facebook-inner">
        <a href="#" class="facebook-link"><i class="fa fa-facebook-square"></i>find us on facebook</a>
    </div>
    <ul class="nav social-nav">
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a href="#"><i class="fa fa-envelope"></i></a></li>
    </ul>
</aside>

colinlboyledotcom/Views/Shared/InstaWidgetPartial.cshtml
<!--Instagram Widget-->
<aside class="col-md-12 col-xs-6 m0 widget widget-instagram hidden-xs">
    <div class="widget-instagram-inner">
        <h5 class="widget-meta"><i class="fa fa-instagram"></i>instagram feed <a href="http://twitter.com/colinboyle">colinboyle</a></h5>
        <div id="instafeed" class="owl-carousel"></div>
    </div>
</aside>

colinlboyledotcom/Views/Shared/TwitterWidgetPartial.cshtml
<!--Twitter Widget-->
<aside class="col-md-12 col-xs-6 widget widget-twitter hidden-xs">
    <div class="widget-twitter-inner">
        <h5 class="widget-meta"><i class="fa fa-twitter"></i>Twitter feed <a href="http://twitter.com/Colin_Boyle">Colin_Boyle</a></h5>
        <div class="row tweet-texts" id="tweets"></div>
        @*<div class="row timepast">1 day ago</div>*@
    </div>
</aside>

colinlboyledotcom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="@Url.Content("~/favicon.ico")" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/vendors.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kanit:500">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans:600,700italic">
    <link href='https://fonts.googleapis.com/css?family=Dosis:400,200,300,500,600,800,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:400,300,300italic,400italic">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500italic,500,700italic,700,900,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Mono:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
    @*
        <!--<environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>-->
    *@
</head>
<body class="home">
    <header class="row black header add-bg affix" data-offset-top="0" id="header">
        <div class="container">
            <div class="row top-header">
                <div class="col-sm-4 col-xs-4 search-form-col">
                    @using (Html.BeginForm("search", "blog", new { id = 1 }, FormMethod.Get, null, new { @class = "search-form" }))
                    {
                        <div class="input-group">
                            <span class="input-group-addon"><img src="/images/search-icon-white.png" alt=""></span>
                            @*<input class="form-control" placeholder="search" type="search" value="searchText">*@
                            @Html.TextBox("searchString", null, new { @class = "form-control", placeholder = "search", type = "search" })
                        </div>
                    }
                </div>

                <a href="@Url.Action("index", "home")" class="col-sm-4 col-xs-4">
                    <div class="logo-col text-center" style="height: 52px; user-select: none;">
                        <svg viewBox="0 0 80 80" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
                            <path id="LeftBrace2" transform="translate(-26.458)" d="m66.146 0-39.688 39.687 39.688 39.688v-2.9475l-36.739-36.739 36.739-36.74z" fill="#f1f0f0" />
                            <text id="CLetter2" x="19.854689" y="36.600784" font-size="22.578px" fill="#f1f0f0">Colin</text>
                            <text id="BLetter2" x="42.763283" y="59.53125" font-size="22.578px" fill="#f1f0f0">Boyle</text>
                            <path id="RightBrace2" transform="translate(-26.458)" d="m66.146 79.375 39.688-39.687-39.688-39.688v2.9475l36.739 36.739-36.739 36.74z" fill="#f1f0f0" />
                            <path id="LLetter2" d="m24.854 54.347 30.888-31.279" stroke="#f1f0f0" stroke-width="2" />
                        </svg>
                    </div>
                </a>

                <div class="col-sm-4 col-xs-4 menu-trigger-col">
                    <button class="menu-trigger pull-right">
                        <span class="active-page">home</span>
                        <img src="/images/menu-align-white.png" alt="" class="icon-burger">
                        <img src="/images/menu-close-white.png" alt="" class="icon-cross">
                    </button>
                </div>
            </div>
        </div>
        <div class="row menu-section">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 menu-col">
                        <div class="row">
                            <ul class="nav column-menu black-bg">
                                <li>@Html.ActionLink("Home", "index", "home")</li>
                                <li>@Html.ActionLink("About", "about", "home")</li>
                                <li>@Html.ActionLink("Contact", "contact", "home")</li>
                                <li>@Html.ActionLink("Gallery", "all", "gallery")</li>
                            </ul>
                            @if (User.Identity.IsAuthenticated)
                            {
                                using (Html.BeginForm("LogOut", "Account", FormMethod.Post, new { id = "logoutForm" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <ul class="nav column-menu black-bg">
                                        <li>
                                            @Html.ActionLink("Hello " + User.Identity.Name + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                                        </li>
                                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                                    </ul>
                                }
                            }
                            else
                            {
                                <ul class="nav column-menu black-bg">
                                    <li><i class="fa fa-sign-in">@Html.ActionLink("Log in", "login", "account")</i></li>
                                    <li><i class="fa fa-user">@Html.ActionLink("Register", "register", "account")</i></li>
                                </ul>
                            }
                        </div>
                    </div>
                    <div class="col-sm-4 subscribe-col">
                        <h5 class="widget-title">subscribe to the newsletter.</h5>
                        <form action="#" method="post" class="form-inline subscribe-form">
                            <div class="form-group">
                                <input class="form-control" placeholder="Email" type="email">
                            </div>
                            <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                        </form>
                        <ul class="nav social-nav dark">
                            <li><a href="https://twitter.com/Colin_Boyle"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="https://www.facebook.com/colin.boyle.927"><i class="fa fa-facebook-official"></i></a></li>
                            <li><a href="https://www.instagram.com/colinboyle/"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="mailto:colin.boyle93@gmail.com"><i class="fa fa-envelope"></i></a></li>
                            <li><a href="sms://+14023120970"><i class="fa fa-mobile"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>


    @RenderBody()


    <!--Footer-->
    <footer class="row" id="footer">
        <div class="container">
            <div class="row top-footer">
                <div class="widget col-sm-3 widget-about">
                    <div class="row m0"><a href="index.html"><img src="/images/Logo2.png" alt="" class="center-block"></a></div>
                </div>
                <div class="widget col-sm-5 widget-menu">
                    <div class="row">
                        <ul class="nav column-menu white-bg">
                            <li class="active">@Html.ActionLink("Home", "index", "home")</li>
                            <li>@Html.ActionLink("About", "about", "home")</li>
                            <li>@Html.ActionLink("Contact", "contact", "home")</li>
                            <li>@Html.ActionLink("Gallery", "all", "gallery")</li>
                        </ul>

                        @if (User.Identity.IsAuthenticated)
                        {
                            using (Html.BeginForm("LogOut", "Account", FormMethod.Post, new { id = "logoutForm" }))
                            {
                                @Html.AntiForgeryToken()
                                <ul class="nav column-menu white-bg">
                                    <li>
                                        @Html.ActionLink("Hello " + User.Identity.Name + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                                    </li>
                                    <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                                </ul>
                            }
                        }
                        else
                        {
                            <ul class="nav column-menu white-bg">
                                <li><i class="fa fa-sign-in">@Html.ActionLink("Log in", "login", "account")</i></li>
                                <li><i class="fa fa-user">@Html.ActionLink("Register", "register", "account")</i></li>
                            </ul>
                        }

                    </div>
                </div>
                <div class="widget col-sm-4 m0 widget-subscribe">
                    <h5 class="widget-title">subscribe to the newsletter</h5>
                    <form asp-controller="Newsletter" asp-action="Subscribe" method="post" class="form-inline subscribe-form">
                        <div class="form-group">
                            @Html.EditorFor(sub => new colinlboyledotcom.Models.Subscriber().email, new { htmlAttributes = new { @class = "form-control", name = "email", placeholder = "Email" } })
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                    </form>
                </div>
            </div>
            <h5 class="copyright"><a href="#">&copy; @DateTime.Now.Year - Colin / Boyle</a></h5>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script src="~/js/site.js"></script>
    @*
        <!--<environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>-->
    *@
</body>
</html>

colinlboyledotcom/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="shortcut icon" type="image/x-icon" href="@Url.Content("~/content/favicon.ico")" />
    <link rel="icon" type="image/ico" href="@Url.Content("~/content/favicon.ico")" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/vendors.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kanit:500">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans:600,700italic">
    <link href='https://fonts.googleapis.com/css?family=Dosis:400,200,300,500,600,800,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:400,300,300italic,400italic">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500italic,500,700italic,700,900,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Mono:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
    @*
        <!--<environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>-->
    *@
</head>
<body class="home">
    <header class="row black header add-bg affix" data-offset-top="0" id="header">
        <div class="container">
            <div class="row top-header">
                <div class="col-sm-4 col-xs-4 search-form-col">
                    @using (Html.BeginForm("search", "blog", new { id = 1 }, FormMethod.Get, null, new { @class = "search-form" }))
                    {
                        <div class="input-group">
                            <span class="input-group-addon"><img src="/images/search-icon-white.png" alt=""></span>
                            @*<input class="form-control" placeholder="search" type="search" value="searchText">*@
                            @Html.TextBox("searchString", null, new { @class = "form-control", placeholder = "search", type = "search" })
                        </div>
                    }
                </div>

                <a href="@Url.Action("index", "home")" class="col-sm-4 col-xs-4">
                    <div id="svglogo" class="logo-col text-center" style="height: 90px; user-select: none;">
                        <svg viewBox="0 0 80 80" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
                            <g>
                                <path id="LeftBrace" transform="translate(-26.458)" d="m66.146 0-39.688 39.687 39.688 39.688v-2.9475l-36.739-36.739 36.739-36.74z" fill="#f1f0f0" />
                                <text id="CLetter" x="19.854689" y="36.600784" font-size="22.578px" fill="#f1f0f0">Colin</text>
                                <text id="BLetter" x="42.763283" y="59.53125" font-size="22.578px" fill="#f1f0f0">Boyle</text>

                                <text id="Science" x="11" y="44" font-size="14px" fill="#f1f0f0">science</text>
                                <text id="Design" x="11" y="44" font-size="14px" fill="#f1f0f0">design</text>
                                <text id="Technology" x="11" y="44" font-size="14px" fill="#f1f0f0">technology</text>
                                <text id="Coding" x="11" y="44" font-size="14px" fill="#f1f0f0">coding</text>

                                <path id="RightBrace" transform="translate(-26.458)" d="m66.146 79.375 39.688-39.687-39.688-39.688v2.9475l36.739 36.739-36.739 36.74z" fill="#f1f0f0" />
                                <path id="LLetter" d="m24.854 54.347 30.888-31.279" stroke="#f1f0f0" stroke-width="2" />
                            </g>
                        </svg>
                    </div>
                </a>
                <div class="col-sm-4 col-xs-4 menu-trigger-col">
                    <button class="menu-trigger pull-right">
                        <span class="active-page">home</span>
                        <img src="/images/menu-align-white.png" alt="" class="icon-burger">
                        <img src="/images/menu-close-white.png" alt="" class="icon-cross">
                    </button>
                </div>
            </div>
        </div>
        <div class="row menu-section">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 menu-col">
                        <div class="row">
                            <ul class="nav column-menu black-bg">
                                <li>@Html.ActionLink("Home", "index", "home")</li>
                                <li>@Html.ActionLink("About", "about", "home")</li>
                                <li>@Html.ActionLink("Contact", "contact", "home")</li>
                                <li>@Html.ActionLink("Gallery", "all", "gallery")</li>
                            </ul>
                            @if (User.Identity.IsAuthenticated)
                            {
                                using (Html.BeginForm("LogOut", "Account", FormMethod.Post, new { id = "logoutForm" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <ul class="nav column-menu black-bg">
                                        <li>
                                            @Html.ActionLink("Hello " + User.Identity.Name + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                                        </li>
                                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                                    </ul>
                                }
                            }
                            else
                            {
                                <ul class="nav column-menu black-bg">
                                    <li><i class="fa fa-sign-in">@Html.ActionLink("Log in", "login", "account")</i></li>
                                    <li><i class="fa fa-user">@Html.ActionLink("Register", "register", "account")</i></li>
                                </ul>
                            }
                        </div>
                    </div>
                    <div class="col-sm-4 subscribe-col">
                        <h5 class="widget-title">subscribe to the newsletter.</h5>
                        <form action="#" method="post" class="form-inline subscribe-form">
                            <div class="form-group">
                                <input class="form-control" placeholder="Email" type="email">
                            </div>
                            <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                        </form>
                        <ul class="nav social-nav dark">
                            <li><a href="https://twitter.com/Colin_Boyle"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="https://www.facebook.com/colin.boyle.927"><i class="fa fa-facebook-official"></i></a></li>
                            <li><a href="https://www.instagram.com/colinboyle/"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="mailto:colin.boyle93@gmail.com"><i class="fa fa-envelope"></i></a></li>
                            <li><a href="sms://+14023120970"><i class="fa fa-mobile"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>


    @RenderBody()


    <!--Footer-->
    <footer class="row" id="footer">
        <div class="container">
            <div class="row top-footer">
                <div class="widget col-sm-3 widget-about">
                    <div class="row m0 center-block"><a href="index.html"><img src="/images/Logo2.png" alt="" class="center-block"></a></div>
                </div>
                <div class="widget col-sm-5 widget-menu">
                    <div class="row">
                        <ul class="nav column-menu white-bg">
                            <li class="active">@Html.ActionLink("Home", "index", "home")</li>
                            <li>@Html.ActionLink("About", "about", "home")</li>
                            <li>@Html.ActionLink("Contact", "contact", "home")</li>
                            <li>@Html.ActionLink("Gallery", "all", "gallery")</li>
                        </ul>
                        @if (User.Identity.IsAuthenticated)
                        {
                            using (Html.BeginForm("LogOut", "Account", FormMethod.Post, new { id = "logoutForm" }))
                            {
                                @Html.AntiForgeryToken()
                                <ul class="nav column-menu white-bg">
                                    <li>
                                        @Html.ActionLink("Hello " + User.Identity.Name + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                                    </li>
                                    <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                                </ul>
                            }
                        }
                        else
                        {
                            <ul class="nav column-menu white-bg">
                                <li><i class="fa fa-sign-in">@Html.ActionLink("Log in", "login", "account")</i></li>
                                <li><i class="fa fa-user">@Html.ActionLink("Register", "register", "account")</i></li>
                            </ul>
                        }
                    </div>
                </div>
                <div class="widget col-sm-4 m0 widget-subscribe">
                    <h5 class="widget-title">subscribe to the newsletter.</h5>
                    <form asp-controller="Newsletter" asp-action="Subscribe" method="post" class="form-inline subscribe-form">
                        <div class="form-group">
                            @Html.EditorFor(sub => new colinlboyledotcom.Models.Subscriber().email, new { htmlAttributes = new { @class = "form-control", name = "email", placeholder = "Email" } })
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                    </form>
                </div>
            </div>
            <h5 class="copyright"><a href="#">&copy; @DateTime.Now.Year - Colin / Boyle</a></h5>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script src="~/js/site.js"></script>

    @*
        <!--<environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>-->
    *@
</body>
</html>